name: Publish

on:
  push:
    tags: [ v* ]

env:
  DOTNET_VERSION: 6.0.x

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup_version.outputs.version }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Version
      id: setup_version
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

    - name: Publish Functions
      run: dotnet publish -c Release -r win-x86 --self-contained false -o ./dist -p:Version=${{ steps.setup_version.outputs.version }} AppService.Acmebot

    - name: Zip Functions
      run: 7z a -mx=9 latest.zip ./dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          latest.zip

  deploy:
    environment: production
    needs: publish
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist

    - name: Upload to Blob
      run: |
        az storage blob upload --auth-mode login -f latest.zip --account-name st5nit6zqzypoyqfunc -c appservice-acmebot -n v4/latest.zip --overwrite
        az storage blob upload --auth-mode login -f latest.zip --account-name st5nit6zqzypoyqfunc -c appservice-acmebot -n v4/${{ needs.publish.outputs.version }}.zip --overwrite
